-- Production bootstrap checklist.
-- This file is intentionally safe by default and does not insert demo users
-- or sample recipes. Use `seed.dev.sql` for local/demo data.
--
-- Recommended production bootstrap:
-- 1. Add your real admin email to `public.admin_emails`.
-- 2. Let that admin sign in once via Google so `profiles` can sync.
-- 3. Import or migrate your actual cookbook data from the app.
--
-- Example statement for a real deployment, to be edited before use:
-- insert into public.admin_emails (email)
-- values ('you@example.com')
-- on conflict (email) do update
--   set updated_at = now();
