export function getAppDom(root = document) {
  const byId = root.getElementById.bind(root);
  const recipeModal = byId('recipeModal');
  const deleteConfirm = byId('deleteConfirm');
  const clearPlanConfirm = byId('clearPlanConfirm');

  return {
    shell: {
      appShell: byId('appShell'),
      loadingPanel: byId('loadingPanel'),
      uiAnnouncements: byId('uiAnnouncements'),
      notificationStack: byId('notificationStack'),
    },
    auth: {
      authBar: byId('authBar'),
      authBarName: byId('authBarName'),
      authBarMeta: byId('authBarMeta'),
      signOutBtn: byId('signOutBtn'),
      loginPanel: byId('loginPanel'),
      loginIntro: byId('loginIntro'),
      googleLoginActions: byId('googleLoginActions'),
      googleLoginBtn: byId('googleLoginBtn'),
      browserTestLoginForm: byId('browserTestLoginForm'),
      browserTestEmail: byId('browserTestEmail'),
      loginMessage: byId('loginMessage'),
      authHint: byId('authHint'),
      accessPanel: byId('accessPanel'),
      accessMessage: byId('accessMessage'),
      configPanel: byId('configPanel'),
    },
    recipes: {
      toggleFormBtn: byId('toggleFormBtn'),
      toggleFavoritesBtn: byId('toggleFavoritesBtn'),
      topBarFavoritesBtn: byId('topBarFavoritesBtn'),
      formContainer: byId('formContainer'),
      formTitle: byId('formTitle'),
      recipeForm: byId('recipeForm'),
      recipeGrid: byId('recipeGrid'),
      searchInput: byId('searchInput'),
      sortSelect: byId('sortSelect'),
      recipeCount: byId('recipeCount'),
      tagFilterPill: byId('tagFilterPill'),
      tagFilterLabel: byId('tagFilterLabel'),
      clearTagFilterBtn: byId('clearTagFilterBtn'),
      titleInput: byId('title'),
      servingsInput: byId('servings'),
      prepTimeInput: byId('prepTime'),
      cookTimeInput: byId('cookTime'),
      categorySelect: byId('category'),
      tagsInput: byId('tags'),
      imageUrlInput: byId('imageUrl'),
      imageFileInput: byId('imageFile'),
      imagePreview: byId('imagePreview'),
      previewImg: byId('previewImg'),
      ingredientsInput: byId('ingredients'),
      instructionsInput: byId('instructions'),
      platingInput: byId('plating'),
      tipsInput: byId('tips'),
      descriptionInput: byId('description'),
      uploadImageBtn: byId('uploadImageBtn'),
      exportBtn: byId('exportBtn'),
      restoreImportBtn: byId('restoreImportBtn'),
      recipeImportBtn: byId('recipeImportBtn'),
      restoreImportFile: byId('restoreImportFile'),
      recipeImportFile: byId('recipeImportFile'),
      migrateLocalBtn: byId('migrateLocalBtn'),
      tagBar: byId('tagBar'),
      tagBarList: byId('tagBarList'),
      tagBarExpand: byId('tagBarExpand'),
    },
    planner: {
      togglePlannerBtn: byId('togglePlannerBtn'),
      weekPlanner: byId('weekPlanner'),
      daysGrid: byId('daysGrid'),
      shoppingList: byId('shoppingList'),
      shoppingSearchInput: byId('shoppingSearchInput'),
      exportShoppingBtn: byId('exportShoppingBtn'),
      clearPlanBtn: byId('clearPlanBtn'),
    },
    modal: {
      overlay: recipeModal,
      content: recipeModal.querySelector('.modal-content'),
      closeBtn: byId('modalCloseBtn'),
      favoriteBtn: byId('modalFavoriteBtn'),
      editBtn: byId('modalEditBtn'),
      cookedBtn: byId('modalCookedBtn'),
      cookedStatus: byId('modalCookedStatus'),
      servingsSelect: byId('modalServings'),
      image: byId('modalImage'),
      title: byId('modalTitle'),
      date: byId('modalDate'),
      headerMeta: byId('modalHeaderMeta'),
      description: byId('modalDescription'),
      ingredients: byId('modalIngredients'),
      instructions: byId('modalInstructions'),
      plating: byId('modalPlating'),
      tips: byId('modalTips'),
      plannerToggle: byId('modalPlannerToggle'),
      plannerPanel: byId('modalPlannerPanel'),
      plannerDay: byId('modalPlannerDay'),
      plannerSlot: byId('modalPlannerSlot'),
      plannerServings: byId('modalPlannerServings'),
      plannerSaveBtn: byId('modalPlannerSaveBtn'),
      plannerCancelBtn: byId('modalPlannerCancelBtn'),
      plannerFeedback: byId('modalPlannerFeedback'),
      ingredientsToggle: byId('ingredientsToggle'),
      ingredientsCount: byId('ingredientsCount'),
      notesSection: byId('modalNotesSection'),
      platingNote: byId('modalPlatingNote'),
      tipsNote: byId('modalTipsNote'),
    },
    deleteDialog: {
      overlay: deleteConfirm,
      content: deleteConfirm.querySelector('.confirm-box'),
      name: byId('deleteConfirmName'),
      confirmBtn: byId('confirmDeleteBtn'),
      cancelBtn: byId('cancelDeleteBtn'),
    },
    clearPlanDialog: {
      overlay: clearPlanConfirm,
      content: clearPlanConfirm?.querySelector('.confirm-box'),
      confirmBtn: byId('confirmClearPlanBtn'),
      cancelBtn: byId('cancelClearPlanBtn'),
    },
    toolbar: {
      toolbarToggle: byId('toolbarToggle'),
      toolbarPanel: byId('toolbarPanel'),
      toolbarOverlay: byId('toolbarOverlay'),
      toolbarClose: byId('toolbarClose'),
    },
  };
}
